title: "PMPP - C++ & AI Infrastructure"
description: "CUDA 并行编程与 AI 基础设施学习笔记"
author: Blueboylee
url: "https://blueboylee.github.io"
baseurl: "/PMPP_cpp_AI_infra"

# 主题
theme: minima

# 构建设置
markdown: kramdown
highlighter: rouge

# 文章永久链接格式
permalink: /:year/:month/:day/:title/

# 导航栏页面
header_pages:
  - about.md
